---
- name: "Debug FreeBSD timezone bsd_tz_debug={{ bsd_tz_debug }}"
  vars:
    msg: |-
      bsd_tz_role_version: {{ bsd_tz_role_version }}


      ansible_architecture {{ ansible_architecture }}
      ansible_os_family {{ ansible_os_family }}
      ansible_distribution {{ ansible_distribution }}
      ansible_distribution_major_version {{ ansible_distribution_major_version }}
      ansible_distribution_version {{ ansible_distribution_version }}
      ansible_distribution_release {{ ansible_distribution_release }}

      bsd_tz_zoneinfo: {{ bsd_tz_zoneinfo }}
      bsd_tz_ntpdate_enable: {{ bsd_tz_ntpdate_enable }}
      bsd_tz_ntpdate_flags: {{ bsd_tz_ntpdate_flags }}
  ansible.builtin.debug:
    msg: "{{ '{}'.format(msg) }}"

# EOF
