---
# tasks for freebsd_timezone

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: bsd_tz_debug | bool
  tags: bsd_tz_debug

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: bsd_tz_rcconf

- name: Import timezone.yml
  ansible.builtin.import_tasks: timezone.yml
  tags: bsd_tz_timezone

- name: Import stat.yml
  ansible.builtin.import_tasks: stat.yml
  when: bsd_tz_stat | bool
  tags: bsd_tz_stat

# EOF
