---
# tasks for freebsd_timezone

- import_tasks: rcconf.yml
  tags: bsd_tz_rcconf

- import_tasks: timezone.yml
  tags: bsd_tz_timezone

- import_tasks: stat.yml
  when: bsd_tz_stat|bool
  tags: bsd_tz_stat

# EOF
...
