---

- name: Configure /etc/rc.conf
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.val }}"
    backup: "{{ timezone_rcconf_backup }}"
  loop: "{{ timezone_rcconf }}"

# EOF
...
