---

- name: Configure /etc/rc.conf
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: '{{ item.regexp }}={{ item.val }}'
    backup: "{{ timezone_rcconf_backup }}"
  loop: "{{ timezone_rcconf }}"

- name: Configure ntpdate in /etc/rc.conf
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: '^\s*{{ item.regexp }}\s*=(.*)$'
    line: '{{ item.regexp }}={{ item.val }}'
    backup: "{{ timezone_rcconf_backup }}"
  loop: "{{ timezone_rcconf_ntpdate }}"
  notify: restart ntpdate

- name: Enable ntpdate
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: '^\s*ntpdate_enable\s*=(.*)$'
    line: 'ntpdate_enable="YES"'
    backup: "{{ timezone_rcconf_backup }}"
  when: ntpdate_enable|lower == "yes"
  notify: enable and start ntpdate

- name: Disable ntpdate
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: '^\s*ntpdate_enable\s*=(.*)$'
    line: 'ntpdate_enable="NO"'
    backup: "{{ timezone_rcconf_backup }}"
  when: ntpdate_enable|lower == "no"
  notify: disable and stop ntpdate

# EOF
...
