---

- name: Configure /etc/rc.conf
  lineinfile:
    dest: "/etc/rc.conf"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}={{ item.val }}"
    backup: yes
  loop:
    - { regexp: "ntpdate_enable",  val: "\"{{ ntpdate_enable }}\"" }
    - { regexp: "ntpdate_flags",  val: "\"{{ ntpdate_flags }}\"" }
    - { regexp: "ntpd_sync_on_start",  val: "\"{{ ntpd_sync_on_start }}\"" }

# EOF
...
