---
- name: Create timezone
  block:

    - name: "Timezone: Create timezone {{ bsd_tz_zoneinfo }}"
      ansible.builtin.command:
        cmd: >
          tzsetup {{ bsd_tz_zoneinfo }}
        creates: /etc/localtime
      register: command_out
      notify: adjust CMOS

    - name: "Timezone: Debug command_result"
      ansible.builtin.debug:
        var: command_out
      when: bsd_tz_debug | bool

  rescue:

    - name: "Timezone: rescue: Debug"
      ansible.builtin.debug:
        msg: |
          [ERR] Create timezone {{ bsd_tz_zoneinfo }} failed:
          {{ ansible_failed_result }}
          End host.

    - name: "Timezone: rescue: End host"
      ansible.builtin.meta: end_host

- name: Change timezone
  block:

    - name: "Timezone: Change timezone to {{ bsd_tz_zoneinfo }}"
      ansible.builtin.shell:
        cmd: >
          if ( ! diff /usr/share/zoneinfo/{{ bsd_tz_zoneinfo }} /etc/localtime );
          then tzsetup {{ bsd_tz_zoneinfo }};
          fi
      register: command_out
      changed_when: command_out.stdout | d('') is search('differ')
      notify: adjust CMOS

    - name: "Timezone: Debug command_out"
      ansible.builtin.debug:
        var: command_out
      when: bsd_tz_debug | bool

  rescue:

    - name: "Timezone: rescue: Debug"
      ansible.builtin.debug:
        msg: |
          [ERR] Change timezone to {{ bsd_tz_zoneinfo }} failed:
          {{ ansible_failed_result }}
          End host.

    - name: "Timezone: rescue: End host"
      ansible.builtin.meta: end_host

# EOF
