---
# handlers freebsd_timezone

- name: Enable and start ntpdate
  ansible.builtin.service:
    name: ntpdate
    state: started
    enabled: true

- name: Disable and stop ntpdate
  ansible.builtin.service:
    name: ntpdate
    state: stopped
    enabled: false

- name: Restart ntpdate
  ansible.builtin.service:
    name: ntpdate
    state: restarted
  when: bsd_tz_ntpdate_enable|bool

# Update the local time CMOS clock and kernel machdep.adjkerntz
# variable when timezone changes occur
- name: Adjust CMOS
  ansible.builtin.command:
    cmd: adjkerntz -a

# EOF
