---
# handlers for freebsd_timezone

- name: enable and start ntpdate
  service:
    name: ntpdate
    state: started
    enabled: true

- name: disable and stop ntpdate
  service:
    name: ntpdate
    state: stopped
    enabled: false

- name: restart ntpdate
  service:
    name: ntpdate
    state: restarted
  when: ntpdate_enable|lower == "yes"

# update the local time CMOS clock and kernel machdep.adjkerntz
# variable when timezone changes occur
- name: adjust CMOS
  command: adjkerntz -a

# EOF
