---
# handlers for freebsd-timezone
    
- name: enable and start ntpdate
  service:
    name: ntpdate
    state: started
    enabled: yes

- name: disable and stop ntpdate
  service:
    name: ntpdate
    state: stopped
    enabled: no

# update the local time CMOS clock and kernel machdep.adjkerntz
# variable when timezone changes occur
- name: adjust CMOS
  command: adjkerntz -a

# EOF
